experiment_name: grbal_HalfCheetah
algo: grbal_lite
env: HalfCheetahCustom-v0 #HopperCustom-v0

train:
  seed: 42
  max_path_length: 1000
  total_env_steps: 10_000
  steps_per_update: 1000
  warmup_fraction: 0.2

  # --- pretrain phase (random data only) ---
  epochs: 100
  batch_size: 512

  # --- dynamics model ---
  hidden_sizes: [512, 512]
  learning_rate: 0.002

  # --- mpc planner ---
  horizon: 10
  n_candidates: 1_000
  discount: 0.99

  # --- inner loop ---
  inner_lr: 0.001
  inner_steps: 100
  recent_window_size : 10

eval:
  # --- evaluation phase ---
  episodes: 1
  seeds: [0,1,2,3,4,5,6,7,8,9]
