experiment_name: grbal_HalfCheetah_rs_1mil
algo: grbal_lite
env: HalfCheetahCustom-v0 #HopperCustom-v0

train:
  seed: 42
  max_path_length: 1000
  total_env_steps: 1_000_000
  steps_per_update: 2_000
  warmup_steps_budget: 20_000

  # --- pretrain phase (random data only) ---
  epochs: 100
  batch_size: 128

  # --- dynamics model ---
  hidden_sizes: [256, 256, 256]
  learning_rate: 0.001

  # --- mpc planner ---
  planner: "rs" # rs cem
  horizon: 10
  n_candidates: 1_000
  discount: 0.99

  # --- Inner loop / shared adaptation hyperparameters ---
  inner_lr: 0.01 # meta
  inner_steps: 1 # meta
  recent_window_size : 32 # meta
  meta_future_length: 32

  # --- meta outer loop ---
  meta_enabled: true
  meta_batch_size: 32
  meta_outer_lr: 0.001 

eval:
  # --- evaluation phase ---
  episodes: 10
  seeds: [0,1,2,3,4,5,6,7,8,9]
