experiment_name: mb_mpc_HC_fastPretrain_ep60_seed_72
algo: mb_mpc
env: HalfCheetahCustom-v0 #HopperCustom-v0 HalfCheetahCustom-v0

train:
  seed: 72
  max_path_length: 1000
  total_env_steps: 80_000
  steps_per_update: 1_000
  warmup_fraction: 0.2

  # --- pretrain phase (random data only) ---

  epochs: 60
  batch_size: 384
  learning_rate: 0.003

  # --- dynamics model ---
  hidden_sizes: [512, 512]

  # --- mpc planner ---
  horizon: 15
  n_candidates: 2_000
  discount: 0.99

eval:
  episodes: 1
  seeds: [0,1,2,3,4,5,6,7,8,9]