experiment_name: mb_mpc_HC
algo: mb_mpc
env: AntCustom-v0 #HopperCustom-v0 HalfCheetahCustom-v0 AntCustom-v0

train:
  seed: 42
  max_path_length: 1000
  total_env_steps: 100_000
  steps_per_update: 5_000
  warmup_steps_budget: 5000

  # --- pretrain phase (random data only) ---
  epochs: 100
  batch_size: 128

  # --- dynamics model ---
  hidden_sizes: [128, 128]
  learning_rate: 0.001

  # --- mpc planner ---
  planner: "cem" # rs cem
  horizon: 10
  n_candidates: 1_000
  discount: 0.99

  # --- outer training loop ---

eval:
  # --- evaluation phase ---
  episodes: 2
  seeds: [0,1,2,3,4,5]
