experiment_name: mb_mpc_HC_cem
algo: mb_mpc
env: HalfCheetahCustom-v0 #HopperCustom-v0 HalfCheetahCustom-v0

train:
  seed: 42
  max_path_length: 1000
  total_env_steps: 100_000
  steps_per_update: 1000
  warmup_fraction: 0.2

  # --- pretrain phase (random data only) ---
  epochs: 100
  batch_size: 512

  # --- dynamics model ---
  hidden_sizes: [256, 256]
  learning_rate: 0.002

  # --- mpc planner ---
  planner: "cem" # rs cem
  horizon: 10
  n_candidates: 1_000
  discount: 0.99

  # --- outer training loop ---

eval:
  # --- evaluation phase ---
  episodes: 1
  seeds: [0,1,2,3,4,5]
