experiment_name: mb_mpc_kstep_k5_lk2p0
algo: mb_mpc_k_step
env: GymAnt-v0
device: auto # cpu or cuda
exclude_current_positions_from_observation: true

train:
  seed: 42
  max_path_length: 1000
  steps_per_iteration: 10_000
  iterations: 25
  eval_interval_steps: 50_000
  train_epochs: 50
  batch_size: 512
  valid_split_ratio: 0.1

  # K-step loss settings (multi-step open-loop loss)
  k_horizon: 5
  lambda_1: 1.0
  lambda_k: 2.0

  dynamics_model:
    hidden_sizes: [512, 512, 512]
    learning_rate: 0.001

  planner:
    type: "cem"
    horizon: 15
    n_candidates: 250
    discount: 0.99
    num_cem_iters: 4
    percent_elites: 0.15
    alpha: 0.20

eval:
  episodes: 10
  seeds: [0,1,2,3,4,5,6,7,8,9]
