experiment_name: mb_mpc_HC_warmHeavy_w35_seed_72
algo: mb_mpc
env: HalfCheetahCustom-v0 #HopperCustom-v0 HalfCheetahCustom-v0

train:
  seed: 72
  max_path_length: 1000
  total_env_steps: 90_000
  steps_per_update: 900
  warmup_fraction: 0.35

  # --- pretrain phase (random data only) ---

  epochs: 90
  batch_size: 512
  learning_rate: 0.0022

  # --- dynamics model ---
  hidden_sizes: [512, 512]

  # --- mpc planner ---
  horizon: 12
  n_candidates: 1_500
  discount: 0.99

  # --- outer training loop ---

eval:
  # --- evaluation phase ---
  episodes: 1
  seeds: [0,1,2,3,4,5,6,7,8,9]
